class Rice {
  static int _idCounter = 0;

  final int id;
  final String title;

  Rice({
    required this.id,
    required this.title,
  });

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'title': title,
    };
  }

  factory Rice.fromMap(Map<String, dynamic> map) {
    return Rice(
      id: map['id'],
      title: map['title'],
    );
  }

  static Rice createSeed({required String title}) {
    final seed = Rice(id: _idCounter++, title: title);
    return seed;
  }

  static List<Rice> getAllSeeds() {
    return [
      Rice.createSeed(title: "NSIC RC150 (TUBIGAN 9) DWSR"),
      Rice.createSeed(title: "NSIC RC152 (TUBIGAN 10) DWSR"),
      Rice.createSeed(title: "NSIC RC134 (TUBIGAN 4) DWSR"),
      Rice.createSeed(title: "NSIC RC144 (TUBIGAN 8) DWSR"),
      Rice.createSeed(title: "NSIC RC196H (MESTISO 16)"),
      Rice.createSeed(title: "NSIC 2010 RC226 (TUBIGAN 20) DWSR"),
      Rice.createSeed(title: "NSIC RC130 (TUBIGAN 3) DWSR"),
      Rice.createSeed(title: "NSIC RC140 (TUBIGAN 6) DWSR"),
      Rice.createSeed(title: "NSIC RC146 (PJ7) DWSR"),
      Rice.createSeed(title: "NSIC RC156 (TUBIGAN 12) DWSR"),
      Rice.createSeed(title: "NSIC RC178H (MESTISO 14)"),
      Rice.createSeed(title: "NSIC RC216 (TUBIGAN 17) DWSR"),
      Rice.createSeed(title: "PSB RC4 (MOLAWIN)"),
      Rice.createSeed(title: "NSIC RC142 (TUBIGAN 7) DWSR"),
      Rice.createSeed(title: "NSIC RC198H (MESTISO 17)"),
      Rice.createSeed(title: "NSIC RC114H (MESTISO 2)"),
      Rice.createSeed(title: "NSIC RC116H (MESTISO 3)"),
      Rice.createSeed(title: "NSIC RC138 (TUBIGAN 5) DWSR"),
      Rice.createSeed(title: "NSIC RC164H (MESTISO 9) RIZALINA"),
      Rice.createSeed(title: "NSIC RC192 (SAHOD ULAN 1)"),
      Rice.createSeed(title: "NSIC RC224 (TUBIGAN 18) DWSR"),
      Rice.createSeed(title: "PSB RC10 (PAGSANJAN)"),
      Rice.createSeed(title: "PSB RC76 (PANAY)"),
      Rice.createSeed(title: "NSIC RC118 (MATATAG 3) TPR"),
      Rice.createSeed(title: "NSIC RC134 (TUBIGAN 4) TPR"),
      Rice.createSeed(title: "NSIC RC136H (MESTISO 7)"),
      Rice.createSeed(title: "NSIC RC144 (TUBIGAN 8) TPR"),
      Rice.createSeed(title: "NSIC RC160 (TUBIGAN 14) DWSR"),
      Rice.createSeed(title: "NSIC RC206H (MESTISO 21)"),
      Rice.createSeed(title: "NSIC 2010 RC228H (MESTISO 24)"),
      Rice.createSeed(title: "NSIC 2010 RC230H (MESTISO 25)"),
      Rice.createSeed(title: "NSIC RC130 (TUBIGAN 3) TPR"),
      Rice.createSeed(title: "PSB RC8 (TALAVERA)"),
      Rice.createSeed(title: "NSIC RC120 (MATATAG 6) TPR"),
      Rice.createSeed(title: "NSIC RC150 (TUBIGAN 9) TPR"),
      Rice.createSeed(title: "NSIC RC152 (TUBIGAN 10) TPR"),
      Rice.createSeed(title: "NSIC RC220 SR (JAPONICA 1)"),
      Rice.createSeed(title: "PSB RC12 (CALIRAYA)"),
      Rice.createSeed(title: "NSIC 2010 RC232H (MESTISO 26)"),
      Rice.createSeed(title: "NSIC RC126H (MESTISO 5)"),
      Rice.createSeed(title: "NSIC RC140 (TUBIGAN 6) TPR"),
      Rice.createSeed(title: "NSIC RC146 (PJ7) TPR"),
      Rice.createSeed(title: "NSIC RC154 (TUBIGAN 11)"),
      Rice.createSeed(title: "NSIC RC166H (MESTISO 10)"),
      Rice.createSeed(title: "NSIC RC180H (MESTISO 15)"),
      Rice.createSeed(title: "NSIC RC202H (MESTISO 19)"),
      Rice.createSeed(title: "NSIC RC214 (TUBIGAN 16) DWSR"),
      Rice.createSeed(title: "PSB RC14 (RIO GRANDE)"),
      Rice.createSeed(title: "PSB RC26H (MAGAT)"),
      Rice.createSeed(title: "PSB RC82 (PEÑARANDA)"),
      Rice.createSeed(title: "NSIC 2010 RC224 (TUBIGAN 19)"),
      Rice.createSeed(title: "NSIC RC112 (TUBIGAN 2)"),
      Rice.createSeed(title: "NSIC RC138 (TUBIGAN 5) TPR"),
      Rice.createSeed(title: "NSIC RC148 (MABANGO 2)"),
      Rice.createSeed(title: "NSIC RC156 (TUBIGAN 12) TPR"),
      Rice.createSeed(title: "NSIC RC162H (MESTISO 8)"),
      Rice.createSeed(title: "NSIC RC200H (MESTISO 18)"),
      Rice.createSeed(title: "NSIC RC204H (MESTISO 20)"),
      Rice.createSeed(title: "NSIC RC212 (TUBIGAN 15) DWSR"),
      Rice.createSeed(title: "PSB RC20 (CHICO)"),
      Rice.createSeed(title: "PSB RC28 (AGNO)"),
      Rice.createSeed(title: "PSB RC78 (PAMPANGA)"),
      Rice.createSeed(title: "PSB RC84 (SIPOCOT)"),
      Rice.createSeed(title: "NSIC 2010 RC226 (TUBIGAN 20) TPR"),
      Rice.createSeed(title: "NSIC RC142 (TUBIGAN 7) TPR"),
      Rice.createSeed(title: "NSIC RC170 (MS 11)"),
      Rice.createSeed(title: "NSIC RC172 (MS 13)"),
      Rice.createSeed(title: "NSIC RC174H (MESTISO 12)"),
      Rice.createSeed(title: "NSIC RC194 (SUBMARINO 1) NORMAL"),
      Rice.createSeed(title: "NSIC RC216 (TUBIGAN 17) TPR"),
      Rice.createSeed(title: "PSB RC32 (JARO)"),
      Rice.createSeed(title: "PSB RC6 (CARRANGLAN)"),
      Rice.createSeed(title: "PSB RC80 (PASIG)"),
      Rice.createSeed(title: "NSIC RC110 (TUBIGAN 1)"),
      Rice.createSeed(title: "NSIC RC132H (MESTISO 6)"),
      Rice.createSeed(title: "NSIC RC158 (TUBIGAN 13)"),
      Rice.createSeed(title: "NSIC RC168H (MESTISO 11)"),
      Rice.createSeed(title: "NSIC RC176H (MESTISO 13)"),
      Rice.createSeed(title: "NSIC RC182 (SALINAS 1)"),
      Rice.createSeed(title: "NSIC RC210H (MESTISO 23)"),
      Rice.createSeed(title: "PSB RC54 (ABRA)"),
      Rice.createSeed(title: "PSB RC60 (TUGATOG)"),
      Rice.createSeed(title: "PSB RC86 (MATNOG)"),
      Rice.createSeed(title: "NSIC 2010 RC236H (MESTISO 28)"),
      Rice.createSeed(title: "NSIC RC188 (SALINAS 4)"),
      Rice.createSeed(title: "NSIC RC222 (TUBIGAN 18) TPR"),
      Rice.createSeed(title: "PSB RC42 (BALIWAG)"),
      Rice.createSeed(title: "PSB RC56 (DAPITAN)"),
      Rice.createSeed(title: "PSB RC70 (BAMBAN)"),
      Rice.createSeed(title: "PSB RC74 (AKLAN)"),
      Rice.createSeed(title: "IR65"),
      Rice.createSeed(title: "IR73885-1-4-3-2-1-6 (MATATAG 9)"),
      Rice.createSeed(title: "NSIC 2010 RC234H (MESTISO 27)"),
      Rice.createSeed(title: "NSIC RC186 (SALINAS 3)"),
      Rice.createSeed(title: "NSIC RC208H (MESTISO 22)"),
      Rice.createSeed(title: "NSIC RC212 (TUBIGAN 15) TPR"),
      Rice.createSeed(title: "PSB RC52 (GANDARA)"),
      Rice.createSeed(title: "IR69726-29-1-2-2-2 (MATATAG 2)"),
      Rice.createSeed(title: "NSIC RC214 (TUBIGAN 16) TPR"),
      Rice.createSeed(title: "PSB RC68 (SACOBIA)"),
      Rice.createSeed(title: "PSB RC88 (NAGA)"),
      Rice.createSeed(title: "PSB RC98 (LIAN)"),
      Rice.createSeed(title: "NSIC RC106 (SUMILAO)"),
      Rice.createSeed(title: "NSIC RC17 (MALAGKIT 3)"),
      Rice.createSeed(title: "PSB RC102 (MAMBURAO)"),
      Rice.createSeed(title: "PSB RC24 (CAGAYAN)"),
      Rice.createSeed(title: "PSB RC62 (NAGUILIAN)"),
      Rice.createSeed(title: "NSIC RC124H (MESTISO 4) BIGANTE"),
      Rice.createSeed(title: "NSIC RC128 (MABANGO 1) (A)"),
      Rice.createSeed(title: "PSB RC100 (SANTIAGO)"),
      Rice.createSeed(title: "PSB RC30 (AGUS)"),
      Rice.createSeed(title: "PSB RC50 (BICOL)"),
      Rice.createSeed(title: "NSIC RC9 (APO)"),
      Rice.createSeed(title: "BPI Ri1"),
      Rice.createSeed(title: "IR60"),
      Rice.createSeed(title: "IR64"),
      Rice.createSeed(title: "IR66"),
      Rice.createSeed(title: "NSIC RC118 (MATATAG 3) DWSR"),
      Rice.createSeed(title: "NSIC RC120 (MATATAG 6) DWSR"),
      Rice.createSeed(title: "NSIC RC13 (MALAGKIT 1)"),
      Rice.createSeed(title: "NSIC RC15 (MALAGKIT 2) WS"),
      Rice.createSeed(title: "NSIC RC184 (SALINAS 2)"),
      Rice.createSeed(title: "NSIC RC190 (SALINAS 5)"),
      Rice.createSeed(title: "(SUBMARINO 1) SUBMERGED"),
      Rice.createSeed(title: "NSIC RC218 SR (MABANGO 3)"),
      Rice.createSeed(title: "NSIC RC122 (ANGELICA)"),
      Rice.createSeed(title: "NSIC RC15 (MALAGKIT 2) DS"),
      Rice.createSeed(title: "PSB RC1 (MAKILING)"),
      Rice.createSeed(title: "PSB RC7 (BANAHAW)"),
      Rice.createSeed(title: "NSIC RC160 (TUBIGAN 14) TPR"),
      Rice.createSeed(title: "PSB RC5 (ARAYAT)"),
      Rice.createSeed(title: "PSB RC18 (ALA)"),
      Rice.createSeed(title: "PSB RC2 (NAHALIN)"),
      Rice.createSeed(title: "PSB RC3 (GINILINGAN PUTI)"),
      Rice.createSeed(title: "PSB RC66 (AGUSAN)"),
      Rice.createSeed(title: "PSB RC72 (MESTISO 1)"),
      Rice.createSeed(title: "PSB RC34 (BURDAGOL)"),
      Rice.createSeed(title: "PSB RC58 (MAYAPA)"),
      Rice.createSeed(title: "PSB RC64 (KABACAN)"),
      Rice.createSeed(title: "PSB RC90 (BUGUEY)"),
      Rice.createSeed(title: "NSIC RC11 (CANLAON)"),
      Rice.createSeed(title: "NSIC RC19 (MALAGKIT 4)"),
      Rice.createSeed(title: "NSIC RC194"),
      Rice.createSeed(title: "PSB RC16 (ENNANO)"),
      Rice.createSeed(title: "PSB RC48 (HAGONOY)"),
      Rice.createSeed(title: "PSB RC36 (MA-AYON)"),
      Rice.createSeed(title: "PSB RC38 (RINARA)"),
      Rice.createSeed(title: "RC NSIC RC156 (TUBIGAN 12) DWSR"),
      Rice.createSeed(title: "PSB RC22 (LILIW)"),
      Rice.createSeed(title: "PSB RC40 (CHAYONG)"),
      Rice.createSeed(title: "UPL Ri1"),
      Rice.createSeed(title: "PSB RC92 (SAGADA)"),
      Rice.createSeed(title: "PSB RC94 (HUNGDUAN)"),
      Rice.createSeed(title: "PSB RC46 (SUMADEL)"),
      Rice.createSeed(title: "PSB RC96 (IBULAO)"),
      Rice.createSeed(title: "PSB RC44 (GOHANG)"),
      Rice.createSeed(title: "NSIC RC104 (BALILI)"),
      Rice.createSeed(title: "RICE100DAYS"),
      Rice.createSeed(title: "RICE110DAYS"),
      Rice.createSeed(title: "RICE120DAYS"),
      Rice.createSeed(title: "RICE130DAYS"),
      Rice.createSeed(title: "NSIC 2011 RC240 (TUBIGAN 22)"),
      Rice.createSeed(title: "TH82"),
      Rice.createSeed(title: "IR74"),
      Rice.createSeed(title: "RICE135DAYS"),
      Rice.createSeed(title: "RICE135DAYS"),
      Rice.createSeed(title: "112DAYS"),
      Rice.createSeed(title: "NSIC 2011 RC238"),
      Rice.createSeed(title: "NSIC 2012 RC298"),
      Rice.createSeed(title: "NSIC 2012 RC300"),
      Rice.createSeed(title: "NSIC 2012 RC302"),
      Rice.createSeed(title: "RC-402"),
    ];
  }
}
